# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('type_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('hp', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('special_attack', models.IntegerField(default=0)),
                ('special_defense', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('generation', models.IntegerField(default=0)),
                ('is_legendary', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('has_gender', models.CharField(max_length=50)),
                ('pr_male', models.CharField(max_length=50)),
                ('egg_group_1', models.CharField(max_length=50)),
                ('egg_group_2', models.CharField(max_length=50)),
                ('has_mega_evolution', models.CharField(max_length=50)),
                ('height_m', models.FloatField(default=0.0)),
                ('weight_kg', models.FloatField(default=0.0)),
                ('catch_rate', models.IntegerField(default=0)),
                ('body_style', models.CharField(max_length=50)),
            ],
        ),
    ]
