# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeVis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('zero_damage', models.CharField(max_length=150)),
                ('normal', models.CharField(max_length=150)),
                ('two_times', models.CharField(max_length=150)),
                ('half_damage', models.CharField(max_length=150)),
            ],
        ),
    ]
